PREFIX rml: <http://semweb.mmlab.be/ns/rml#>
PREFIX ql: <http://semweb.mmlab.be/ns/ql#>
PREFIX foaf: <http://xmlns.com/foaf/spec/>
PREFIX schema: <http://schema.org/>
PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX nlon: <http://lod.nl.go.kr/ontology/>
PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX saws: <http://purl.org/saws/ontology#>
PREFIX swc: <http://data.semanticweb.org/ns/swc/ontology#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>

SELECT ?n2
WHERE {
    ?k bibo:isbn ?i .
    ?k dc:title ?t .
    ?k schema:author ?a . # join __
    ?k bibo:editor ?e . # join __
    ?a foaf:firstName ?fn .
    ?a foaf:lastName ?ln .
    #?a rdf:type nlon:Author .
    ?a vivo:Institute ?in . # join __
    ?in rdfs:label ?n1 .
    ?in a vivo:Institute . # type __
    ?e rdfs:label ?n2 .
    ?e rdf:type saws:Editor . # type
    ?c a swc:Chair .
    ?c dul:introduces ?r . # join
    ?c foaf:firstName ?cfn .
    ?r schema:reviews ?k .
}
 # ?r, ?k, ?in, ?a, ?e !!!! ?c
